#
# broker.yml
#
# Simple yaml file for the env specific configuration of the broker connections.
# See the wiki for more information: http://code.google.com/p/activemessaging/wiki/Configuration
#
development:
    ############################
    # Stomp Adapter Properties #
    ############################
    adapter: stomp
    host: linode.iachieved.it
    reliable:  true
#    heartBeat: 10000,10000

test:
    adapter: test
    reliable: false

production:
    adapter: stomp
    reliable: true
    # properties below are all defaults for this adapter
    # login: ""
    # passcode: ""
    # host: localhost
    # port: 61613
    # reliable: true
    # reconnectDelay: 5
